### ISSUE TITLE
Provide Information about how to obtain/prepare data

### ISSUE THREAD

**Issue by angrybobcat** [RyanEricLamb/rugby-score-prediction#1]
Nice demo-project!

I just played around a bit and realized that on current master, the db is missing - which I could fix by digging it out from older commits.
With the db, the app works but data-preparation still fails since theres some .csv missing.
If you could add some detailed information about how to build up the db and the remaining data for preparation from scratch that would be super nice!

**Comment by RyanEricLamb** [comment]
Thank you, glad you found this interesting! Unfortunately the original data source has been shut down since this project was developed.
