### ISSUE TITLE
What is the project license? 

### ISSUE THREAD

**Issue by tamagusko** [RyanEricLamb/rugby-score-prediction#3]
Amazing job. It would be interesting to specify the license of use.

**Comment by RyanEricLamb** [comment]
Thank you, glad you enjoyed it! I've added the licence file  - this project uses the GNU AGPLv3 license but the
TrueSkill(TM) brand does not. Microsoft permits only Xbox Live games or non-commercial projects to use TrueSkill(TM). If your project is commercial, you should find another rating system.

Details of the TrueSkill project by Heungsub Lee and it's license can be viewed here: https://github.com/sublee/trueskill/blob/master/LICENSE

**Comment by tamagusko** [comment]
Perfect Ryan! Thank you and keep up the good work! 

Take Care!
